import { PrismaClient } from './src/generated/prisma/index.js';

const prisma = new PrismaClient();

const mentors = [
  {
    "name": "Adria Starkey",
    "status": "Available",
    "businessName": "FineMark National Bank & Trust",
    "title": "Executive Vice President and President",
    "location": null,
    "phone": null,
    "email": "AStarkey@finemarkbank.com",
    "biography": "Adria D. Starkey is Executive Vice President and President of FineMark National Bank & Trust (Collier County). Previously, she served as Chief Operating Officer of The Sanibel Captiva Trust Company. She has been a FineMark Director since 2013.\n\nMrs. Starkey is a graduate of the University of Florida. She completed her post-graduate work at Florida International University, the University of Miami, and the University of North Carolina.\n\nAppointed to the Florida Prepaid College Board by Governor Rick Scott, Mrs. Starkey also serves on the boards of The HealthCare Network Foundation, Gulfshore Playhouse, and Friends of Baker Park.\n\nMrs. Starkey serves in an emeritus capacity for Naples Children and Education Foundation and The Shelter for Abused Women and Children. She also serves on the advisory board of the Lutgert College of Business, the advisory council for Angels Undercover, and is a mentor for Champions for Learning.\n\nIn 2000, Mrs. Starkey was named Woman of the Year by Gulfshore Life and Woman of Achievement by The Community Foundation. She received the Edison College Leadership in Fostering Education award in 2008.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Marketing"
    ],
    "sectorExpertise": [],
    "programs": [
      "ENT Classes",
      "CEO Club"
    ],
    "workStatus": "Working",
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "Justin Schepke",
    "veteranStatus": false
  },
  {
    "name": "Andrew Townsend",
    "status": "Available",
    "businessName": "Cattyshack Cafe",
    "title": "Owner",
    "location": null,
    "phone": null,
    "email": "andrew@cattyshackcafe.com",
    "biography": "Andrew Townsend, an FGCU alumnus ('18, Business Management), co-founded Cattyshack Cat Café in June 2020 with his partner, Amber Redfern. Located in the Gulf Coast Town Center in Fort Myers, Florida, Cattyshack uniquely combines a traditional café experience with a dedicated space for adoptable cats, aiming to address the issue of overcrowded animal shelters by facilitating cat adoptions. Instagram+8FGCU 360+8The News-Press+8\nBefore launching Cattyshack, Townsend and Redfern conducted extensive market research, visiting 20 cat cafés across six states to refine their concept. They also organized a successful Kickstarter campaign, raising over $20,000 from 230 supporters in 30 days. Since its opening, Cattyshack has facilitated the adoption of over 2,375 cats, working closely with the Gulf Coast Humane Society to provide a comfortable environment for both the cats and café visitors.",
    "fgcuAlumni": true,
    "domainExpertise": [
      "Franchising",
      "Licenses",
      "Marketing",
      "Business Development"
    ],
    "sectorExpertise": [
      "Retail",
      "Hospitality",
      "Media"
    ],
    "programs": [
      "Runway Program",
      "Veterans Florida",
      "ENT Classes",
      "Unassigned",
      "DMD Classes"
    ],
    "workStatus": "Working",
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "McKenna M Houston",
    "veteranStatus": false
  },
  {
    "name": "Anthony\tBotta",
    "status": "Available",
    "businessName": "Hubspot.",
    "title": "Account Executive",
    "location": null,
    "phone": "19548058589",
    "email": "gators1avb@gmail.com",
    "biography": "Software Sales",
    "fgcuAlumni": true,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": "Justin Schepke, McKenna M Houston",
    "veteranStatus": false
  },
  {
    "name": "Becky Sharon",
    "status": "Available",
    "businessName": "The Plenary Mind Institute",
    "title": "Owner",
    "location": "11181 Health Park Blvd # 1170, Naples, Florida 34110, Naples, Fl 34110, US",
    "phone": null,
    "email": "becky@theplenarymindinstitute.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Bill Motzer",
    "status": "Available",
    "businessName": "Public Accountant",
    "title": "Advisor",
    "location": null,
    "phone": "2679920256",
    "email": "wmotzer@comcast.net",
    "biography": "Retiring at the end of 2014, Bill Motzer began his career in Public Accounting in New York City before transitioning to the corporate sector after three years. With a business background spanning over 45 years, he has held key leadership roles across multiple industries.\nThroughout his career, Bill has served as CFO, COO, and CEO, primarily at the operating company level, working for a privately held specialty manufacturer in the pharmaceutical industry. He later advanced to Executive VP and CFO at the corporate level, where he and the CEO managed a diverse portfolio of companies. His expertise lies in privately held, midsized businesses with revenues ranging from $25 million to $700 million.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Finance",
      "Business Development",
      "Accounting",
      "Operations",
      "Acquisitions"
    ],
    "sectorExpertise": [
      "Healthcare",
      "Construction",
      "Wholesale Distribution",
      "Marketing"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Brian Rist",
    "status": "Available",
    "businessName": "Ris Family Foundation",
    "title": "Chair",
    "location": null,
    "phone": "12395657737",
    "email": "brist@ristfamilyfoundation.org",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [
      "Unassigned",
      "Runway Program",
      "Veterans Florida",
      "ENT Classes",
      "CEO Club"
    ],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Brian Strojny",
    "status": "Available",
    "businessName": "Putting Veterans First",
    "title": "Founder",
    "location": null,
    "phone": null,
    "email": "bstrojny@yahoo.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Carl Koko",
    "status": "Available",
    "businessName": "Sport Industry Management |",
    "title": "Advisor",
    "location": null,
    "phone": null,
    "email": "carlkoko98@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Dennis Lemus",
    "status": "Available",
    "businessName": "Hinge Health",
    "title": "Senior Client Success Manager",
    "location": null,
    "phone": null,
    "email": "dennislemus@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Erv Pesek",
    "status": "Available",
    "businessName": "Common Sense Consultants, Inc.",
    "title": "Owner",
    "location": null,
    "phone": null,
    "email": "ervpesekjr@aol.com",
    "biography": "Erv Pesek has been a dedicated mentor and judge at FGCU’s School of Entrepreneurship for over eight years, guiding students in the classroom, Runway Program, and Military Program while consulting for student businesses. With a strong background in business strategy, he founded Common Sense Consultants (CSC) to support startups and growing companies, and Marketing Products Group (MPG), specializing in national corporate identity and incentive programs.\nHis extensive corporate career includes serving as Executive VP/GM of the St. Louis Storm (a professional indoor soccer team), Corporate Director of Marketing & Sales at Bass Pro Shops, and holding senior marketing leadership roles at Anheuser-Busch, managing brand licensing, corporate identity, and Busch Entertainment operations. He pursued corporate education at The Wharton School, studied Industrial Psychology at Georgia Tech, and earned a Psychology degree with a Science minor from Quincy University.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Marketing",
      "Business Development",
      "Sales"
    ],
    "sectorExpertise": [
      "Consumer Products"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "crobb@fgcu.edu",
    "veteranStatus": false
  },
  {
    "name": "Fred Quinn",
    "status": "Available",
    "businessName": "Quest Specialty Chemicals",
    "title": "Founder",
    "location": null,
    "phone": "6178037414",
    "email": "questchem@aol.com",
    "biography": "Fred Quinn is an Operating Partner Emeritus at Huron Capital with extensive experience in business growth, acquisitions, and strategic leadership. In 2003, he co-founded Quest Specialty Chemicals, a company focused on specialty coatings, adhesives, and sealants. As CEO (2003-2012), he played a pivotal role in scaling the company through a combination of strategic acquisitions and organic growth, expanding revenues from a startup level to $125 million.\nFollowing his tenure as CEO, Fred continued as Chairman (2012-2014), overseeing Quest’s expansion to $300 million in revenue and solidifying its position in the industry. His expertise in private equity, business transformation, and market-driven growth strategies has made him a valuable leader in the investment and corporate sectors. As an Operating Partner at Huron Capital, he continues to contribute his insights to portfolio companies, guiding them toward sustainable success.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Finance",
      "Business Development",
      "Acquisitions"
    ],
    "sectorExpertise": [
      "Healthcare"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "crobb@fgcu.edu",
    "veteranStatus": false
  },
  {
    "name": "Gonzalo\tPaternoster",
    "status": "Available",
    "businessName": "Tech & AI",
    "title": "CEO",
    "location": null,
    "phone": null,
    "email": "gonzalo4life@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Jamaree\tJones",
    "status": "Available",
    "businessName": "Youth Advocate",
    "title": "Advisor",
    "location": null,
    "phone": null,
    "email": "jamareetjones@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Julio Barina",
    "status": "Available",
    "businessName": "Markham Norton Mosteller Wright & Company",
    "title": "Partner",
    "location": null,
    "phone": null,
    "email": "jbarina@markham-norton.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Justin Schepke",
    "status": "Available",
    "businessName": "FitBet Challenges LLC",
    "title": "Owner",
    "location": null,
    "phone": null,
    "email": "jschepke@fgcu.edu",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Karen Mosteller",
    "status": "Available",
    "businessName": "Markham, Norton, Moesteller, Wright and Company PA",
    "title": "Partner",
    "location": null,
    "phone": null,
    "email": "kmosteller@markham-norton.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [
      "Marketing",
      "Sales",
      "Business Development"
    ],
    "sectorExpertise": [
      "Retail",
      "Hospitality",
      "Media"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Katherine Waddell",
    "status": "Available",
    "businessName": "Katherine Waddell Consulting",
    "title": "Owner",
    "location": null,
    "phone": "3177533814",
    "email": "kathy@kwaddellconsulting.com",
    "biography": "Kathy Waddell's marketing career began in 1979 when she co-founded Morey & Waddell, Inc., Indianapolis’ first fee-based marketing and advertising agency. As President, she led brand strategy, marketing campaigns, and client development across industries including restaurant, insurance, retail, and politics. After 14 successful years, she sold the firm and launched Katherine Waddell Consulting, using unique research methods to help CEOs optimize their marketing strategies in rebranding.\nIn Indiana, Kathy served as President of a top ten United Way Agency and mentored entrepreneurs through Butler University’s Real Business Experience. Now residing in Florida, Kathy mentors in the New Venture Lab and served as a judge in the Runway and Veteran’s programs at FGCU.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Marketing"
    ],
    "sectorExpertise": [
      "Marketing"
    ],
    "programs": [
      "Runway Program",
      "Unassigned",
      "Veterans Florida",
      "CEO Club"
    ],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Ken Mack",
    "status": "Available",
    "businessName": "KAPLAN-MACK",
    "title": "CPA & CFF",
    "location": null,
    "phone": null,
    "email": null,
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Kena Yoke",
    "status": "Available",
    "businessName": "Island Piling, Inc.",
    "title": "Vice President Business Strategy",
    "location": null,
    "phone": null,
    "email": "kena@islandpiling.com",
    "biography": "Kena Yoke brings over 40 years of expertise in construction management, office administration, and project coordination, coupled with a lifelong commitment to networking and community engagement. As Vice President of Island Piling, Inc. and Managing Member of Island Piling Manufacturing, LLC, she leads with a focus on innovation and excellence. Previously, she founded Kena Yoke Consulting, Inc. (formerly Kena Yoke Bookkeeping), pioneering virtual office solutions after the 2007–2008 financial crisis. Her consultancy helped businesses streamline operations, enhance public image, and strengthen community ties. An entrepreneur and “socialpreneur,” Kena has held leadership roles with Fusion Pointe, the Entrepreneur Society of Naples (Executive Director), and the Entrepreneur Society of America, while actively supporting the FGCU Veteran Entrepreneur Program and FGCU Runway initiatives.\nBeyond business, Kena is deeply committed to service and philanthropy. She actively engages with organizations such as St. Matthew’s House, Above Board Chamber of Commerce, Collier-Lee Honor Flight, Freedom Waters Foundation, and the Louisville Slugger Warriors. Her dedication to the veteran community stems from her father’s WWII Navy service, a history she fully uncovered only after his passing. Recognizing the vital need for veterans to stay connected, she has devoted herself to building strong support networks through partnerships with organizations, businesses, and individuals, ensuring a safe and supportive environment for veterans.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Administration",
      "Project Management",
      "Networking"
    ],
    "sectorExpertise": [
      "Construction",
      "Philanthropy"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Kent Lloyd",
    "status": "Available",
    "businessName": "Rapid Emotional",
    "title": "Advisor",
    "location": null,
    "phone": "12393485417",
    "email": "kent.lloyd11@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Kevin McCauley",
    "status": "Available",
    "businessName": "Hero Real Estate & Co.",
    "title": "Real Estate Broker",
    "location": null,
    "phone": null,
    "email": "kevin@hero-re.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Mark Pruskauer",
    "status": "Available",
    "businessName": "Coolair Conditioning, Inc.",
    "title": "President",
    "location": null,
    "phone": null,
    "email": "markpruskauer@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": "crobb@fgcu.edu",
    "veteranStatus": false
  },
  {
    "name": "Nick Romano",
    "status": "Available",
    "businessName": "Romano Shutters Company",
    "title": "Managing Director",
    "location": null,
    "phone": null,
    "email": "nromano@earthlink.net",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Patrick Neale",
    "status": "Available",
    "businessName": "Patrick Neale & Associates, Attorneys",
    "title": "Owner",
    "location": null,
    "phone": null,
    "email": "pneale@fgcu.edu",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Quay Longs",
    "status": "Available",
    "businessName": "Strive Hall",
    "title": "Entrepreneurial Educator | CEO,",
    "location": null,
    "phone": null,
    "email": "quaylo26@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Ricardo\tAlexis",
    "status": "Available",
    "businessName": "Entrepreneurship Coach",
    "title": "Advisor",
    "location": null,
    "phone": null,
    "email": "ricardoalex42@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Robert Smith",
    "status": "Available",
    "businessName": "Global Restaurant Superstore",
    "title": "Sales",
    "location": null,
    "phone": null,
    "email": "bsmith@rfsmithlaw.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Rod\tEly",
    "status": "Available",
    "businessName": "RelyMagical LLC",
    "title": "Owner",
    "location": null,
    "phone": "8023104541",
    "email": "Rely571@gmail.com",
    "biography": "Rod was on the leadership Team at Green Mountain Coffee Roasters (and Keurig) for over 20 years. He worked closely with the Retiring at the end of 2014, Bill Motzer began his career in Public Accounting in New York City before transitioning to the corporate sector after three years. With a business background spanning over 45 years, he has held key leadership roles across multiple industries.\nThroughout his career, Bill has served as CFO, COO, and CEO, primarily at the operating company level, working for a privately held specialty founder (Bob Stiller) especially in the early years when the company was $30MM in Sales with 250 employees. His leadership helped propel the company to over $4BB in Sales with over 7000 employees in North America, recognized as the #1 performing stock on NASDAQ in the 21st century (up a +7,895% in 15 years). He was instrumental in developing the Website (internet top 100 retailer) that sells over $500MM in Keurig brewers, and other Beverages (www.keurig.com, www.greenmountaincoffee.com) yearly, Rod was in charge of all software/systems and process for the company as it grew. He was recognized as an industry leader which earned him a seat on the Customer Advisory board for PeopleSoft and Oracle along with an article in Oracle Magazine in 2010. His experience covers Marketing, New Product introduction/go to market strategy, software development, process engineering, costing, financials, human resources, roasting and process control software and customer relationship management. \nOn the Entrepreneurship side, Rod and his brother Ray owned a real estate development and rental business in Vermont. Rod believed that diversification in income was the key to success and early retirement. His dreams came true at age 55 when he was able to retire, move to FL, join a Golf and Tennis Club and begin working with Sandra Kauanui at FGCU developing and growing the Entrepreneurship program (which his son experienced in 2014 as an undergrad) into the DKSOE",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Sales",
      "Management",
      "Product Development"
    ],
    "sectorExpertise": [
      "Retail",
      "Consumer Products"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "Deleted outdated pending user",
    "veteranStatus": false
  },
  {
    "name": "Ron\tWilson",
    "status": "Available",
    "businessName": "SCORE Naples",
    "title": "Business Counselor",
    "location": null,
    "phone": "12398879739",
    "email": "ronaldiwilson@yahoo.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Ron\tSidman",
    "status": "Available",
    "businessName": "Green Mountain Coffee Roasters/Keurig",
    "title": "Owner",
    "location": null,
    "phone": "7742389173",
    "email": "rjsidman@gmail.com",
    "biography": "Rod was on the leadership Team at Green Mountain Coffee Roasters (and Keurig) for over 20 years. He worked closely with the founder (Bob Stiller) especially in the early years when the company was $30MM in Sales with 250 employees. His leadership helped propel the company to over $4BB in Sales with over 7000 employees in North America, recognized as the #1 performing stock on NASDAQ in the 21st century (up a +7,895% in 15 years). He was instrumental in developing the Website (internet top 100 retailer) that sells over $500MM in Keurig brewers, and other Beverages (www.keurig.com, www.greenmountaincoffee.com) yearly, Rod was in charge of all software/systems and process for the company as it grew. He was recognized as an industry leader which earned him a seat on the Customer Advisory board for PeopleSoft and Oracle along with an article in Oracle Magazine in 2010. His experience covers Marketing, New Product introduction/go to market strategy, software development, process engineering, costing, financials, human resources, roasting and process control software and customer relationship management. \nOn the Entrepreneurship side, Rod and his brother Ray owned a real estate development and rental business in Vermont. Rod believed that diversification in income was the key to success and early retirement. His dreams came true at age 55 when he was able to retire, move to FL, join a Golf and Tennis Club and begin working with Sandra Kauanui at FGCU developing and growing the Entrepreneurship program (which his son experienced in 2014 as an undergrad) into the DKSOE",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Business Model Design",
      "Leadership",
      "Management",
      "Product Development"
    ],
    "sectorExpertise": [
      "Consumer Products"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "Deleted outdated pending user",
    "veteranStatus": false
  },
  {
    "name": "Ryan Boddy",
    "status": "Available",
    "businessName": "Red Ventures",
    "title": "Senior Frontend Developer",
    "location": null,
    "phone": null,
    "email": "ryanboddyweb@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Scott Sharon",
    "status": "Available",
    "businessName": "Scott Sharon Consulting",
    "title": "Owner",
    "location": null,
    "phone": null,
    "email": "scott@scottsharon.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Steve Aronson",
    "status": "Available",
    "businessName": "Star Consultants",
    "title": "Owner",
    "location": null,
    "phone": null,
    "email": "saronson6@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Steven Niehaus",
    "status": "Available",
    "businessName": "Edison Business Advisors",
    "title": "M&A Advisor",
    "location": null,
    "phone": null,
    "email": "steve@edisonBA.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Xavier Henry",
    "status": "Available",
    "businessName": "Live Entertainment",
    "title": "Advisor",
    "location": null,
    "phone": null,
    "email": "xjhenry92@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": "Deleted outdated pending user",
    "veteranStatus": false
  },
  {
    "name": "Ted\tSachs Jr",
    "status": "Available",
    "businessName": "Edward M. Sachs, Jr. Financial",
    "title": "Former Managing Director and investor",
    "location": null,
    "phone": null,
    "email": "edwardsachsjr@gmail.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Susi Kimball",
    "status": "Available",
    "businessName": "Fifth Avenue Family Office",
    "title": "Client Services",
    "location": null,
    "phone": "2392625248",
    "email": "susi@fifthavenuefamily.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Ray Albright",
    "status": "Available",
    "businessName": "Crito Capital LLC",
    "title": "Owner",
    "location": null,
    "phone": null,
    "email": "ray.albright@critocapital.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Timothy\tCartwright",
    "status": "Available",
    "businessName": "Fifth Avenue Family Office",
    "title": "Partner and Co-Founder",
    "location": null,
    "phone": null,
    "email": "tim@fifthavenuefamily.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Paula Garber McNulty",
    "status": "Available",
    "businessName": "Business Coach",
    "title": "Advisor",
    "location": null,
    "phone": null,
    "email": null,
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Zach Kielbasa",
    "status": "Available",
    "businessName": "Ox Strong Moving Franchising and Ox Strong Moving",
    "title": "Owner",
    "location": null,
    "phone": null,
    "email": null,
    "biography": "Zach Kielbasa is a driven entrepreneur who turned down a six-figure job at 22 to launch a dating app, which saw initial success before ultimately failing. Undeterred, he founded Ox Strong Moving in Gainesville, FL, with just $20 in his bank account. At 23, he expanded operations to Fort Myers, initially dispatching jobs from an FGCU fraternity house. By 24, his company generated $1.5 million in revenue across two locations, leading him to focus on streamlining operations.\nAt 25, Zach opened a third location in Fort Lauderdale, treating it as a model for future franchising. Now 26, he remains the sole owner of Ox Strong Moving and Ox Strong Moving Franchising, preparing to launch four franchises in 2025. With a long-term vision of 200 franchises by 2032, Zach is committed to building thousands of leaders along the way.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Sales",
      "Marketing",
      "People Development"
    ],
    "sectorExpertise": [
      "Transportation",
      "Media"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "Deleted outdated pending user",
    "veteranStatus": false
  },
  {
    "name": "Jade Gibson",
    "status": "Available",
    "businessName": "Jade Strings & Jewel Booth",
    "title": "Owner",
    "location": null,
    "phone": null,
    "email": null,
    "biography": "Jade Gibson ('19) has pursued her passion for music since childhood, refining her talent to perform with renowned groups like The Who and Cirque Du Soleil. While music initially led her to Florida Gulf Coast University, she later discovered an interest in entrepreneurship, recognizing the potential to turn her artistry into a successful business.\nIn 2018, she founded Jade Strings, a company providing professional live music for special events. Seeing a demand for high-quality musical performances and first-class service across Southwest Florida and beyond, she leveraged her skills and business acumen to build a thriving venture, combining her love for music with entrepreneurial success.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Marketing",
      "Business Development"
    ],
    "sectorExpertise": [
      "Entertainment",
      "Hospitality",
      "Media"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "Deleted outdated pending user",
    "veteranStatus": false
  },
  {
    "name": "Justin Fiorello",
    "status": "Available",
    "businessName": "Xcite Automotive",
    "title": "Account Representative",
    "location": null,
    "phone": null,
    "email": null,
    "biography": "Justin Fiorello, also known as Justin Fio, is a 22-year-old entrepreneur and social media influencer originally from New Jersey, currently residing in Florida. He is pursuing a degree in entrepreneurship at Florida Gulf Coast University.  \nJustin has built a significant online presence, with over 70,000 subscribers on YouTube and 191,000 followers on TikTok, where he shares content primarily focused on diesel trucks and his daily life. In late 2020, he launched the Justin Fio Brand, offering merchandise such as hats, decals, t-shirts, and hoodies. In addition to his online ventures, Justin owns Fio's Dumpster Services, a business providing waste management solutions in the Sarasota, Florida area.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Business Development",
      "Marketing",
      "Product Development",
      "Sales"
    ],
    "sectorExpertise": [
      "Media",
      "Transportation"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "Deleted outdated pending user",
    "veteranStatus": false
  },
  {
    "name": "Don Platt",
    "status": "Available",
    "businessName": "Office Products (Various Companies)",
    "title": "Advisor",
    "location": null,
    "phone": null,
    "email": null,
    "biography": "Don Platt has built a 50-year career founding and co-founding multiple companies across diverse industries, gaining extensive expertise in product development, acquisitions, and strategic growth. Early in his career at Procter & Gamble, he played a key role in the development and national launch of Pringles Potato Chips, focusing on consumer testing and market strategy. He later transitioned to radio station management, earning a reputation for turning around failing stations and launching startups as VP & General Manager at ABC FM. As VP of Acquisitions and later CFO of U.S. Office Products, he led its IPO and spearheaded 247 acquisitions across multiple industries, growing revenues from $30 million to over $2 billion. Eventually promoted to EVP of Strategic Planning, he managed 40% of non-core business operations and executed the largest simultaneous IPO in Wall Street history, creating six independent publicly traded entities.\nPlatt co-founded 1-800-Pack-Rat, raising $20 million in initial capital and using franchising to expand to 25 locations and $30 million in revenues. Amid the 2008 financial crisis, he transitioned to COO, restructuring the company by repurchasing all franchise locations and converting operations to company-owned and managed. By his 2015 retirement, the company had 70 warehouses, 40,000 containers in circulation, and over $120 million in revenue. Holding an MBA in Marketing & Finance from Stanford, he has emphasized data-driven decision-making, forecasting, and budgeting throughout his career. Committed to mentorship, he has been an early mentor for Fusion Pointe and an advisor to Collier County’s Incubator Program, regularly speaking and judging at entrepreneurial pitch competitions.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Finance",
      "Franchising",
      "Acquisitions"
    ],
    "sectorExpertise": [
      "Entertainment",
      "Media",
      "Transportation"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "Deleted outdated pending user",
    "veteranStatus": false
  },
  {
    "name": "Anthony Smolen",
    "status": "Available",
    "businessName": "Independent Board Member and Mentor",
    "title": "Advisor",
    "location": null,
    "phone": null,
    "email": null,
    "biography": "Anthony Smolen is a seasoned Certified Public Accountant specializing in assurance, tax, and specialty advisory services for closely held businesses and high-net-worth clients. With expertise in complex estate, tax, and business planning, he has served a diverse range of industries, including manufacturing, hospitality, real estate, construction, leasing/financing, and not-for-profit organizations. After earning his Bachelor of Science in Accounting from Niagara University, Anthony began his career at a large regional accounting firm in Buffalo before founding his own CPA firm in 1976. Over the next 35 years, his firm grew into a trusted provider of financial services, serving some of Western New York’s most prominent companies.\nThroughout his career, Anthony has maintained the highest professional standards, participating in the triennial Peer Review Program of the American Institute of Certified Public Accountants and consistently receiving unmodified opinions. He is an active member of both the AICPA and the New York State Society of CPAs and has held numerous community affiliations. In addition to his client work, Anthony serves on advisory boards and acts as an outsourced Chief Financial Officer for a major real estate company. His commitment to excellence and strategic financial planning has made him a respected leader in his field.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Finance",
      "Sales",
      "Management"
    ],
    "sectorExpertise": [
      "Accounting",
      "FP&A"
    ],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": "Deleted outdated pending user",
    "veteranStatus": false
  },
  {
    "name": "Danielle Russo-Slugh",
    "status": "Available",
    "businessName": "Tamiami Angel Fund",
    "title": "Director of Fund Operations",
    "location": null,
    "phone": "6464314950",
    "email": null,
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Scott Reif",
    "status": "Available",
    "businessName": "Infinite Growth Group",
    "title": "Managing Partner",
    "location": null,
    "phone": "2398210676",
    "email": "srelf@fgcu.edu",
    "biography": "Consulting with start-up and growth companies.",
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [
      "Veterans Florida"
    ],
    "workStatus": null,
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Jim Smith",
    "status": "Available",
    "businessName": "Help.com",
    "title": "President",
    "location": "10501 FGCU Blvd, Fort Myers, FL 33965, USA",
    "phone": "12768061111",
    "email": "test@test.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [
      "Project Management"
    ],
    "sectorExpertise": [
      "Media"
    ],
    "programs": [
      "Veterans Florida",
      "DMD Classes"
    ],
    "workStatus": "Retired",
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Jim Oberweis",
    "status": "Available",
    "businessName": "Oberweis for Congress",
    "title": "Candidate",
    "location": "Bonita Bay, Bonita Springs, FL, USA",
    "phone": "12399137100",
    "email": "JimOberweis1@gmail.com",
    "biography": "Jim Oberweis is a successful entrepreneur and common sense conservative.  Over the course of his four-decade career as a small businessman, he’s helped create thousands of jobs.  He’s committed to helping reform our government.  A native of Aurora, Illinois, Jim graduated from Marmion Military Academy before going on to earn a B.A. from the University of Illinois at Champaign-Urbana and, later, an M.B.A. from the University of Chicago Graduate School of Business.  Jim launched a career in the financial services industry.  Today, Oberweis Asset Management manages approximately $5 billion in growth stock assets and is now run by his son.\nJim also served as the Chairman of Oberweis Dairy until 2022.\nIn 2012 he was elected to the Illinois State Senate and was reelected in 2016, eventually rising to minority whip.  \nJim is well known for his philanthropic endeavors. More than two decades ago, he established the Oberweis Foundation as a charitable trust created to help children and adults in difficult economic circumstances, such as those served by Hesed House in Aurora and the Northern Illinois Food Bank, on whose board of directors Jim served, and the Harry Chapin Food Bank.  He has been a very active supporter of ProjectHood in Chicago which is working to keep kids out of gangs and away from drugs, and to reduce the street violence in Chicago.  The Oberweis Foundation has provided significant financial support to the Wonder Gardens in Bonita Springs, the Everglades Foundation, and The Club for Growth, \nIn 2021 Jim moved full time to Bonita Springs where he and wife have owned a condominium for 16 years, and became a Florida resident. Jim has been married to his wife Julie for 18 years.  Between them they have seven adult children and 26 grandchildren.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Finance"
    ],
    "sectorExpertise": [
      "Consumer Products"
    ],
    "programs": [
      "Runway Program"
    ],
    "workStatus": "Working",
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Robert F. Smith",
    "status": "Available",
    "businessName": "Robert F. Smith, Attorney at Law, LLC",
    "title": "Sole Proprietor",
    "location": "Bonita Springs, FL, USA",
    "phone": "16309405628",
    "email": "bsmith@rfsmithlaw.com",
    "biography": null,
    "fgcuAlumni": false,
    "domainExpertise": [
      "Fundraising",
      "Project Management"
    ],
    "sectorExpertise": [
      "Healthcare",
      "Biotechnology"
    ],
    "programs": [
      "Runway Program"
    ],
    "workStatus": "Part Time",
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Michael Schneider-Christians",
    "status": "Available",
    "businessName": "Emboros Trading & Consulting, LLC",
    "title": "owner/manager",
    "location": "Cape Coral, FL, USA",
    "phone": "12398513975",
    "email": "mschneiderchristians@gmail.com",
    "biography": "I have been involved with the Veterans Program since the early days.  I think it all started 2016.   I have had up to 4 veterans during their 12-week sessions as a mentor.  Those ZOOM sessions were beneficial for all involved as we all learned from one another.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "International Business"
    ],
    "sectorExpertise": [
      "Marketing"
    ],
    "programs": [
      "Veterans Florida"
    ],
    "workStatus": "Retired",
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Bruce Bacon",
    "status": "Available",
    "businessName": "Applied Handling Inc & Shure Star L.L.C.",
    "title": "Owner",
    "location": "Naples, FL, USA",
    "phone": "13135900432",
    "email": "BruceBacon7@gmail.com",
    "biography": "3 - startup companies\n1- CEO for 42 years at Applied Handling",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Leadership"
    ],
    "sectorExpertise": [
      "Wholesale Distribution"
    ],
    "programs": [
      "Runway Program"
    ],
    "workStatus": "Part Time",
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Jay Brown",
    "status": "Available",
    "businessName": null,
    "title": null,
    "location": "Florida Gulf Coast University (FGCU, FGCU Boulevard, Fort Myers, FL, USA",
    "phone": "14846808801",
    "email": "jaymbrown@me.com",
    "biography": "I am a retired professional who has spent most of my career in the financial service industry, first focused on technology and then on product development. After leaving the corporate world I consulted with non-profit and business start-ups before co-founding a healthy food home delivery service and then worked with an urban farm and garden store in Philadelphia. My work with start-ups has been focused in two primary areas; product development and internal organization and process. I currently live in Bonita Springs with my wife Barb Doyne and our golden retriever Autumn.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Product Development",
      "Project Management"
    ],
    "sectorExpertise": [],
    "programs": [
      "Unassigned"
    ],
    "workStatus": "Retired",
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Ron Davids",
    "status": "Available",
    "businessName": "Davids & Cohen, PC",
    "title": "Counsel",
    "location": "Fort Myers, FL, USA",
    "phone": "18572252299",
    "email": "rdavids1956@gmail.com",
    "biography": "I have been an attorney since 1981.  I attended Colby College as an undergraduate and graduated from Boston University School of Law.  I worked for a large law firm in Boston for nearly 18 years and was as a partner for the last 12 years there.  In 1998, I started my own law firm and have been there ever since.  We have 18 lawyers and various paralegals, secretaries and office staff.  My practice has focused on a few different areas.  I have litigated several civil cases and have been lead counsel on over twenty-five lengthy trials.  My areas of concentration in my early years involved defending product liability cases for large manufacturers such as General Motors, Komatsu and Nintendo.  I also represented software companies in intellectual product and trade secret cases, real estate developers in property disputes and employers in alleged discrimination and other workplace issues.  I retired from the fulltime practice a few years ago and now spend my winters in Bonita Springs.  Since that time, I have continued to advise clients on business matters, including the drafting, review and negotiation of a wide variety of contracts as well as consulting on ongoing litigation matters.",
    "fgcuAlumni": false,
    "domainExpertise": [
      "Project Management",
      "Networking",
      "Management",
      "Leadership",
      "Marketing",
      "Business Development",
      "People Development"
    ],
    "sectorExpertise": [],
    "programs": [
      "Unassigned",
      "Runway Program",
      "Veterans Florida"
    ],
    "workStatus": "Retired",
    "potentialSpeaker": true,
    "potentialJudge": true,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Randall Reade",
    "status": "Available",
    "businessName": "The Washignton DC ArchAngels",
    "title": "Executive Vice President",
    "location": "503 4th St SE, Washington, DC, USA",
    "phone": "12024225241",
    "email": "Rreade503@gmail.com",
    "biography": "Co-Founded The Washington DC ArchAngels, an organization designed to find and coach early stage innovative companies and present them to angel investors. I have held many investor and entrepreneurship workshops and trained dozens of people..  I am active on Quora.com, and have answered thousands of question on the topic of early stage companies, innovation, ecosystems, entrepreneurship and venture capital, and my answered have received over eight million views. I have mentored dozens of companies at Founder Institute, accelerators at George Mason University and many other accelerators. I have been a speaker on a variety of topics for entrepreners, and taught classes on writing term sheets and company valuation.",
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  },
  {
    "name": "Michael Horowitz",
    "status": "Available",
    "businessName": null,
    "title": null,
    "location": "9074 Sorreno Court, Naples, FL, USA",
    "phone": "12039804413",
    "email": "mhorowitzct@aol.com",
    "biography": "See Judith Jack Bio attached above.",
    "fgcuAlumni": false,
    "domainExpertise": [],
    "sectorExpertise": [],
    "programs": [],
    "workStatus": null,
    "potentialSpeaker": false,
    "potentialJudge": false,
    "mentorCoordinator": null,
    "veteranStatus": false
  }
];

async function main() {
  console.log('Deleting existing mentors...');
  await prisma.mentor.deleteMany();
  
  console.log('Inserting ' + mentors.length + ' mentors...');
  for (const m of mentors) {
    await prisma.mentor.create({ data: m });
  }
  
  const count = await prisma.mentor.count();
  console.log('Done! Total mentors in database:', count);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
